theme: jekyll-theme-merlot
name: 3innie's website
description: Chronicles of my advanture in coding and open source.
highlighter: rouge
url: https://3innielee.github.io/
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap